# welcome to numpy code


In [102]:
import numpy as np



In [103]:
myarr=np.array([[3,6,32,7]])

In [104]:
myarr

array([[ 3,  6, 32,  7]])

# for mamory mangement we can also define data limite of data intered 
# in the arr by writing dtypes=int8 ,int32 ....so on

In [105]:
my=np.array([3,35,62,34],np.int64)

In [106]:
my

array([ 3, 35, 62, 34], dtype=int64)

In [107]:
my[0]

3

# to know the data type and size we use .shape , .dtype

In [108]:
my.shape

(4,)

In [109]:
myarr.shape

(1, 4)

In [110]:
my.dtype

dtype('int64')

In [111]:
myarr

array([[ 3,  6, 32,  7]])

# To change values in the arr

In [112]:
myarr[0,1]=45

In [113]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation methods in numpy 

** There are 6 general mechanisms for creating arrays:

Conversion from other Python structures (i.e. lists and tuples)

Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

Replicating, joining, or mutating existing arrays

Reading arrays from disk, either from standard or custom formats

Creating arrays from raw bytes through the use of strings or buffers

Use of special library functions (e.g., random) **

# Conversion from other Python structures (i.e. lists and tuples)

In [114]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [115]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
listarray.shape

(3, 3)

In [117]:
listarray.size

9

In [118]:
listarray.dtype

dtype('int32')

# Intrinsic NumPy array creation functions
# (e.g. arange, ones, zeros, etc.)

In [119]:
zero=np.zeros((2,5))

In [120]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [121]:
rng=np.arange(15)

In [122]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [123]:
lspace=np.linspace(1,100,10)

In [124]:
lspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [125]:
emp =np.empty((4,6))
#it fill random elemnt

In [126]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11260280e-306, 1.95819673e-306, 1.15710427e-306],
       [6.23056330e-307, 2.22526399e-307, 6.23053614e-307,
        1.29060871e-306, 6.23055651e-307, 1.06811422e-306],
       [3.56043054e-307, 1.37961641e-306, 9.45697982e-308,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 6.23053614e-307,
        1.60221072e-306, 1.42410974e-306, 8.34445561e-308]])

In [127]:
emp_like=np.empty_like(lspace)
#it will return the passed array and now you can edite array

In [128]:
emp_like

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [129]:
ide=np.identity(45)

In [130]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [131]:
ide.shape

(45, 45)

In [132]:
ide.size

2025

In [133]:
arr=np.arange(99)

In [134]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [135]:
arr=arr.reshape(3,33)

In [136]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [137]:
# now to convert it into 1 D arr we use reval()
arr=arr.ravel()

In [138]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [139]:
arr.shape

(99,)

# Concept of axis 

*** There are to type of Axis in 2D array 
first is Axis 0 which indicate row
and second is axis 1 which indicate columen ***

In [140]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [141]:
v=np.array(x)

In [142]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
v.sum(axis=0)
# in this 1+4+7=12

array([12, 15, 18])

In [144]:
v.sum(axis=1)

array([ 6, 15, 24])

*** now to make any array transpose we use arr.T ***

In [145]:
v.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [146]:
v.flat

In [147]:
for item in v.flat:
    print(item)


1
2
3
4
5
6
7
8
9


In [148]:
#to know dimention
v.ndim

2

In [149]:
v.size

9

In [150]:
v.nbytes
# total biye consume

36

In [151]:
one =np.array([3,5,7,645,75])

In [152]:
one.argmax()
# it give index of max element

3

In [153]:
one.argmin()
# it give index of min element

0

In [154]:
# to short the element index in inreasing order  we have argsort()
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [155]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
v.argmax()

8

In [157]:
v.argmin()

0

In [158]:
v.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [159]:
v.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [160]:
v.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [161]:
v.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
v.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [163]:
v


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
v2=np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
v+v2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [166]:
v*v2
#matrix multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [167]:
np.sqrt(v)
#for sqare root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [168]:
v.sum()

45

In [169]:
v.min()

1

In [170]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
# we can allso write such type of statement  using where
np.where(v>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [172]:
np.count_nonzero(v)

9

In [173]:
np.nonzero(v)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [174]:
import sys

In [175]:
py_ar=[0,4,55,2]

In [176]:
np_ar=np.array(py_ar)

In [177]:
sys.getsizeof(1)*len(py_ar)

112

In [178]:
np_ar.itemsize*np_ar.size

16

*** you can see that numpy take much less space ***

***